name = "Jhonatan David Zuñiga Gilon"
rol = "Fullstack Developer"
email = "gizudajhovi@gmail.com"
phone = "(+57) 323 485 038"
birthday = "May 20, 2004"
location = "Cauca, Colombia"
avatar = "./config/assets/avatars/avatar-1.png"
username = "jhonatandzg" # <-- github user name
googlemaps = "URL here !! " 
presentation = """

Poseo tres años de experiencia aprendiendo de manera
autodidacta, en la universidad y en cursos intensivos. Estoy
comprometido con el aprendizaje continuo de nuevas tecnologías y
habilidades que me permitan desarrollarme profesionalmente.
Mi mayor fortaleza es mi capacidad de aprender rápidamente
y resolver problemas de manera creativa. Me apasiona seguir
adquiriendo conocimientos que me permitan alcanzar cada objetivo
que me propongo.
Mi aspiración a mediano plazo es alcanzar un nivel Senior,
dominando las tecnologías más demandadas y aplicando mis
conocimientos en proyectos que generen un impacto positivo.
Mi enfoque se centra en adquirir las habilidades requeridas en cada
caso concreto, dejando de lado títulos o experiencia laboral previa.
Confío en que mi compromiso con el aprendizaje y mi capacidad de
resolución de problemas me diferenciarán como profesional.

"""